Typography.OpenFont/Tables.AdvancedLayout/GPOS.cs

Take Y coordinate of anchor position of base glyph into account, in addition to the Y coordinate of the mark glyph's anchor position.
This is similar to what is done for the X coordinate.
This is required for proper rendering of certain Hebrew diacritics. For example, in the [Alef font](http://alef.hagilda.com/), for the character HEBREW LETTER FINAL KAF (unicode code point 0x05da), diacritics rendered underneath letters should be rendered well above the normal height used for other letters (see below for proper rendering).

fixed Y-axis in mark-to-base positioning

---

Typography.OpenFont/CharacterMap.cs
Typography.OpenFont/Tables.AdvancedLayout/GDEF.cs
Typography.OpenFont/Tables/Cmap.cs
Typography.OpenFont/Tables/Utils.cs

This change allows to at least load the Segoe UI Emoji font (seguiemj.ttf)
with limited support for its features but without throwing.

Warn about some unimplemented features instead of throwing.

---

Typography.GlyphLayout/GlyphIndexList.cs
Typography.GlyphLayout/GlyphLayout.cs
Typography.GlyphLayout/UserCharToGlyphIndexMap.cs
Typography.OpenFont/CharacterMap.cs
Typography.OpenFont/Tables.AdvancedLayout/GSUB.SubTables.cs
Typography.OpenFont/Typeface.cs

In many places, "char" is not a valid type to handle characters, because it
only supports 16 bits. In order to handle the full range of Unicode characters,
we need to use "int".
This allows characters such as 🙌 or 𐐷 to be treated as single codepoints even
though they are encoded as two "char"s in a C# string.

Try to handle "codepoints" instead of "characters".

---

Typography.OpenFont/Tables.TrueType/Glyf.cs

When a composite glyph depends on another composite glyph which has not been
computed yet, we need to interrupt what we are doing and ensure the dependent
glyph is created first.
This patch fixes the loading of font Segoe UI Semibold (seguisb.ttf).

Fix a crash in composite glyph resolution.

---

Typography.OpenFont/CharacterMap.cs
Typography.OpenFont/Tables/Cmap.cs

Use binary search instead of sequential lookup; we now do only 11
or 12 tests per character in Segoe UI Emoji instead of 1300.
Other standard fonts typically have 100 to 200 encoded ranges,
so we only need to do 7 or 8 tests instead of 100 to 200.

Optimise glyph lookups in fonts (format 4 and format 12).

---

Build/N20/Typography.OpenFont/Typography.OpenFont.csproj
Demo/Windows/PixelFarmSample.WinForms/Form1.Designer.cs
Demo/Windows/PixelFarmSample.WinForms/Form1.cs
Demo/Windows/PixelFarmSample.WinForms/PixelFarm/DevVxsTextPrinter.cs
Typography.GlyphLayout/GlyphSubtitution.cs
Typography.OpenFont/OpenFontReader.cs
Typography.OpenFont/Tables.AdvancedLayout/COLR.cs
Typography.OpenFont/Tables.AdvancedLayout/CPAL.cs
Typography.OpenFont/Tables.AdvancedLayout/GSUB.cs
Typography.OpenFont/Tables/Utils.cs
Typography.OpenFont/Typeface.cs
Typography.OpenFont/Typography.OpenFont.projitems

This feature allows to read ligatures in large fonts, and particularly
the Emoji ligatures.
This commit also adds a way for client applications to apply ligature
substitutions on an IGlyphIndexList.

Implement LookupType 7 Lookup tables.

---

Build/Android/Typography.GlyphLayout/Typography.GlyphLayout.csproj
Build/Android/Typography.OpenFont/Typography.OpenFont/Typography.OpenFont.csproj
Build/IOS/Typography.OpenFont/Typography.OpenFont.csproj
Build/N20/Typography.OpenFont/Typography.OpenFont.csproj
Build/NetCore/Typography.OpenFont/Typography.OpenFont/Typography.OpenFont.csproj

I cannot build the project in Release mode without this option, using MonoDevelop or Visual Studio 2017 Community.

Build with /unsafe in release builds, too.

---

Typography.OpenFont/Tables.AdvancedLayout/CPAL.cs

This will break rendering until #62 is fixed, but it is the correct code.

Return correct RGBA color order in the CPAL table.

---

Typography.OpenFont/Tables.AdvancedLayout/GSUB.cs

The ligature was always tested against the first glyph instead
of advancing the lookup in the glyph list.

Fix a bug in substitution lookup type 4.

---

Build/N20/Typography.GlyphLayout/Typography.GlyphLayout.csproj
Build/N20/Typography.OpenFont/Typography.OpenFont.csproj
Demo/Shared/DevTextPrinter/FontManagement.cs
Demo/Shared/DrawingGL.Common.shproj
Demo/Windows/GdiPlusSample.WinForms/Form1.cs
Demo/Windows/GlyphTess.WinForms/GlyphTess.WinForms.csproj
Demo/Windows/PixelFarmSample.WinForms/Form1.cs
Demo/Windows/TextBoxSample.WinForms/Form2.cs
Demo/Windows/TextBoxSample.WinForms/TextBoxSample.WinForms.csproj
PixelFarm.Typography/1.1_Drawing_Fonts/FontManagement.cs
PixelFarm.Typography/2_Drawing_Text/OpenFontStore.cs
PixelFarm/PixelFarm.Vectors/PixelFarm.Vectors.csproj
Typography.GlyphLayout/Typography.GlyphLayout.shproj
Typography.OpenFont/Typography.OpenFont.shproj

Use tools version 14.0 instead of 15.0 in project files, as 15.0 is
not yet supported by mainstream MonoDevelop.
Replace LoadWindowsSystemFonts() with a generic LoadSystemFonts() that
queries recursively for most common font locations, and does not throw
when the directory does not exist.
Also remove a non-portable string.StartsWith("\0") construct.

Fix the Linux port

---

Typography.OpenFont/Tables.AdvancedLayout/CoverageTable.cs
Typography.OpenFont/Tables.AdvancedLayout/GSUB.cs

Implement substitutions that involve both backtracking and lookahead,
and apply the proper number of substitutions (not just the first one).
Get rid of CoverageTable.IsInRange() because that method is no longer
needed and it did not do really do what it was designed for.

GSUB: fix coverage-based glyph contexts

---

Typography.OpenFont/Tables.AdvancedLayout/CoverageTable.cs
Typography.OpenFont/Tables.AdvancedLayout/GPOS.cs

Make formats 1 and 2 two different classes to avoid the need for a switch
in FindPosition(). Get rid of the RangeRecord class because it is a lot
faster to perform a binary search inside integer arrays.
Also make the debug functions a bit nicer.

CoverageTable: optimisations and improvements

---

Typography.GlyphLayout/GlyphLayout.cs
Typography.OpenFont/CharacterMap.cs
Typography.OpenFont/OpenFontReader.cs
Typography.OpenFont/Tables/Cmap.cs
Typography.OpenFont/Tables/Utils.cs
Typography.OpenFont/Typeface.cs

I am not really happy with this code, please consider it a proof of concept for now. The idea behind Cmap format 14 is that glyph resolution can be modified by the following Unicode character (see [Unicode Variant Forms](https://en.wikipedia.org/wiki/Variant_form_(Unicode))). It is a bit like ligatures, but must operate *before* GSUB substitution.
Example with the emoji 👩🏿‍⚕️ “Woman Health Worker: Dark Skin Tone”:
* Unicode sequence: `U+1f469 U+1f3ff U+200d U+2695 U+fe0f`
* Character to glyph (without cmap 14): `1125 1088 390 9649 665`
* Character to glyph (with cmap 14): `1125 1088 390 9649`
* After first ligature: `1136 390 9649`
* After second ligature: `8717`
Before, the sequence would give two glyphs, `8717 665`, and was incorrectly rendered.

Feature: cmap format 14

---

Typography.GlyphLayout/GlyphLayout.cs

Advance width was incorrectly calculated in snap to grid mode, and pixel scale
was applied to the glyph coordinates value but not the glyph advance.

Fix two bugs in GenerateGlyphPlan().

---

Build/NetStandard/FontAtlas/FontAtlas.csproj
Build/NetStandard/Typography.Contours/Typography.Contours.csproj
Build/NetStandard/Typography.GlyphLayout/Typography.GlyphLayout.csproj
Build/NetStandard/Typography.MsdfGen/Typography.MsdfGen.csproj
Build/NetStandard/Typography.OpenFont/Typography.OpenFont.csproj
Build/NetStandard/Typography.TextBreak/Typography.TextBreak.csproj
Build/NetStandard/Typography.TextFlow/Typography.TextFlow.csproj
Build/NetStandard/Typography.TextServices/Typography.TextServices.csproj
Demo/iOS/Xamarin.iOS.GLES2/Xamarin.IOS.GLES2.csproj
Typography.OpenFont/Tables.CFF/CFF.cs
Typography.OpenFont/Tables.CFF/CffEvaluationEngine.cs
Typography.OpenFont/Tables.CFF/Type2CharStringParser.cs
Typography.OpenFont/Tables/Post.cs

For Typography.MsdfGen, .NET Standard 1.0 can be used because it does not need FileStream etc like OpenFont or TextBreak.
Also changed Console to Debug because they are simply more accurate.

Change .NET Standard projects to use .NET Standard 1.3

---

Typography.OpenFont/AdditionalInfo/AdobeGlyphList.cs
Typography.OpenFont/AdditionalInfo/MacPostFormat1.cs

The HexNumber style allows preceding and trailing white spaces, so no need to trim the string.

Use InvariantCulture everywhere

---

Typography.TextBreak/Typography.TextBreak/EngBreakingEngine.cs

**Note:** EngBreakingEngine claims to support char codes 1 to 255, however it cannot handle when char.IsControl(c). When char.IsControl(c) is handled, then all chars between 1 and 255 will not cause NotSupportedExceptions.

Fix NotSupportedException when multiple out of range chars are encountered

---

Typography.TextBreak/Typography.TextBreak.UnitTests/TextBreakTests.csproj
Typography.TextBreak/Typography.TextBreak.UnitTests/app.config
Typography.TextBreak/Typography.TextBreak.UnitTests/packages.config
Typography.TextBreak/Typography.TextBreak/CustomBreaker.cs

So that I can use it without referencing the .NET Framework 2.0 version of System.Memory

Use NuGet package instead of .NET Framework 2.0 version in TextBreakerTests

---

Typography.GlyphLayout/GlyphLayout.cs
Typography.OpenFont/Tables.AdvancedLayout/GPOS.Others.cs
Typography.OpenFont/Tables.AdvancedLayout/GPOS.cs

Hi! Here is some long overdue work on GPOS tables to improve Emoji support for family ligatures. Not complete, but it seems to cover everything in the current Emoji standard. There is still a problem with emojis such as `|👨‍👧‍👦‍👦|` (caused by subtable 7 format 2 not fully implemented, though I already did almost all of the work) but these are Windows extensions and not part of the Emoji standard AFAIK.

GPOS updates

---

Build/N20/Typography.OpenFont/ExtensionAttribute.cs
Build/N20/Typography.TextBreak/ExtensionAttribute.cs

Without this minor fix, building with _e.g._ .NET Framework 4.0 gives the following warning:
3>CSC : warning CS1685: The predefined type 'ExtensionAttribute' is defined in multiple assemblies in the global alias; using definition from 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
There is already the same `#if` in `Build/N20/Typography.OpenFont/ExtensionAttribute.cs`.

Do not redefine ExtensionAttribute with recent enough .NET frameworks.
